FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN dotnet tool install --global dotnet-ef

ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /src

COPY . .

RUN dotnet restore "Triply.Api/Triply.Api.csproj"

CMD ["dotnet", "ef", "database", "update", "--project", "Triply.Infrastructure", "--startup-project", "Triply.Api"]