FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base

USER root

RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

USER $APP_UID

WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Triply.Api/Triply.Api.csproj", "Triply.Api/"]
COPY ["Triply.Application/Triply.Application.csproj", "Triply.Application/"]
COPY ["Triply.Domain/Triply.Domain.csproj", "Triply.Domain/"]
COPY ["Triply.Infrastructure/Triply.Infrastructure.csproj", "Triply.Infrastructure/"]
RUN dotnet restore "Triply.Api/Triply.Api.csproj"
COPY . .
WORKDIR "/src/Triply.Api"
RUN dotnet build "./Triply.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Triply.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Triply.Api.dll"]
