FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN dotnet tool install --global dotnet-ef

ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /workspace

COPY . .

RUN dotnet restore src/Triply.sln

CMD ["dotnet", "ef", "database", "update", "--project", "src/Triply.Infrastructure", "--startup-project", "src/Triply.Api"]