name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request: 
    branches: ["main", "develop"]

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 10.0.x
            
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  email-worker:
    name: Build Email Worker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/EmailWorker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 10.0.x
            
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  image-worker:
    name: Build Image Worker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ImageWorker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 10.0.x
            
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  expire-bookings-worker:
    name: Build Expire Pending Bookings Worker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ExpirePendingBookings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 10.0.x
            
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  message-queue-library:
    name: Build Message Queue Library
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libraries/MessageQueue/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 10.0.x
            
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  logging-library:
    name: Build Logging Library
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libraries/Logging/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 10.0.x
            
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

  frontend:
      name: Build Frontend
      runs-on: ubuntu-latest
      defaults:
          run:
              working-directory: ./frontend
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: npm
            cache-dependency-path: ./frontend/package-lock.json

        - name: Install dependencies
          run: npm ci

        - name: Build frontend
          run: npm run build

  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend image
        run: docker build -t triply-backend ./src

      - name: Build Migrations image
        run: docker build -t triply-migrations ./src --file ./src/Dockerfile.Migrations

      - name: Build Email Worker image
        run: docker build -t triply-email-worker ./src/EmailWorker

      - name: Build Image Worker image
        run: docker build -t triply-image-worker ./src/ImageWorker

      - name: Build Expire Pending Bookings Worker image
        run: docker build -t triply-expire-bookings-worker ./src/ExpirePendingBookings

      - name: Build Frontend image
        run: docker build -t triply-frontend ./frontend

  docker-compose:
    name: Build Docker Compose images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: docker compose build